mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),

]

polls/urls.py
from django.urls import path

from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='d'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='r'),
    path('<int:question_id>/vote/', views.vote, name='v'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
def __str__(self):
    return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question, Choice
from django.views import generic
# Create your views here.
from django.urls import reverse
from django.http import HttpResponse , HttpResponseRedirect


class IndexView(generic.ListView ):
    template_name='polls/index.html'
    context_object_name='latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView ):
    model=Question
    template_name='polls/detail.html'

class ResultsView(generic.DetailView ):
    model=Question
    template_name='polls/Results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:r', args=[question_id]))

templates/polls/detail.html
{% extends 'polls/poll.html' %}

{% block content %}

    <div class="panel panel-success ">
      <br>
      <br>
<hr>

        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
            
                    
                    {{ question.question_text }}
                    {% if error_message %} <span class="label btn-danger">{{ error_message }}</span> {% endif%} 
                    <br>
                    <hr>
            
                        <form action=" {% url 'polls:v' question.id %} " method="POST">
                            {% csrf_token %}
                            {% for choice in question.choice_set.all %}
                            <input type="radio" name="choice" id="choice" {{ forloop.counter }} value="{{choice.id}}" >
                            <label for="choice" {{ forloop.counter }} >{{ choice.choice_text }} </label>
                            <br>
                            {% endfor %}
                            <input class="btn btn-success" type="submit" value="Vote">
                        </form>
            
                      
                </div>

            </div>
        </div>

    </div>

{%  endblock %}

templates/polls/index.html
{% extends 'polls/poll.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
           PULLING APP
        </div>
        <div class="panel-body">
            {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:d' question.id %} ">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}

        </div>

    </div>

{%  endblock %}

templates/polls/poll.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" >
    <!-- Bootstrap CSS -->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %} ">
   
  </head>
  <body>
    <div class="content-wrapper">
     
     <section class="content">
       <div class="container">
          {% block content %}
          {% endblock %}
       </div>

     </section>

    </div>
  </div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
  </body>
</html>

templates/polls/results.html
{% extends 'polls/poll.html' %}

{% block content %}

    <div class="panel panel-success ">
      <br>
      <br>
<hr>

        <div class="panel-body">
            <div class="row">
                <div class="col-lg">
            
                    
                    <div class="card card-default">

                            <h1 class="card-header">{{ question.question_text }}</h1>

                        <ul>
                        {% for choice in question.choice_set.all %}
                            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                        {% endfor %}
                        </ul>
                        
                        <a href="{% url 'polls:d' question.id %}">Vote again?</a>

                    </div>
            
                      
                </div>

            </div>
        </div>

    </div>

{%  endblock %}